### ISSUE TITLE
Symmetries of the spheres independent of the universe?

### ISSUE THREAD

**Issue by marcbezem** [marcbezem/SnSymm#3]
@UlrikBuchholtz @nicolaikraus @pierrecagne @bidundas @DanGrayson :
In relation to a discussion on the symmetry book it occurred to me that it is not a priory clear that $S^n =_U S^n$ is independent of $U$. But I think this follows from our results. Worth mentioning?

**Comment by nicolaikraus** [comment]
Interesting question. Is $U$ assumed to be univalent? The type $S^n \simeq S^n$ doesn't mention $U$, so it's not clear to me how it can depend on $U$. Or is your point that the equality type of $S^n$ itself depends on the universe in which $S^n$ is inductively defined? I would have expected that this isn't the case because the induction principle of an inductive type allows us to eliminate into _any_ type family, no matter its size.

Concretely, does the following argument have a step that doesn't work? I write $S^n_U$ for the HIT $S^n$, defined in universe $U$.
1. $S^n_U$ is equivalent to the $n$-sphere in the lowest universe lifted to universe $U$. This justifies writing $S^n$ instead of $S^n_U$.
2. $S^n =_U S^n$ is $S^n \simeq S^n$ by univalence, which is independent of $U$.

**Comment by marcbezem** [comment]
@nicolaikraus You are right, $S^n \simeq S^n$ doesn't mention $U$, so univalence gives already that all $S^n =_U S^n$ are equivalent (and now I understand Pierre's comment on [github.com](https://github.com/UniMath/SymmetryBook/issues/182) better). In other words, your argument works.

**Comment by pierrecagne** [comment]
I concur. The type of equivalences is universe independent (as soon as the type of function is, which is usually  the case), and then univalence saves the day.

**Comment by marcbezem** [comment]
Thanks everybody! My conclusion is that we need not say something about this in the paper. I'm closing this issue, but don't hesitate to reopen if you disagree.
